guess_my_words_workspace/play/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "start#index"

  resources :plays,  only: [:index]

end

guess_my_words_workspace/play/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

guess_my_words_workspace/play/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

guess_my_words_workspace/play/app/controllers/plays_controller.rb
class PlaysController < ApplicationController

  def index
    @all_words = ["Buku", "Roti", "Kartu" , "Makan"]

    if params[:play].present?
    
      @check = params[:play][:guess] == params[:play][:keyword].downcase
    
      if @check
        flash[:success] = "That's correct"
      else
        flash[:danger] = "That's Wrong"
      end
    end

  end

end

guess_my_words_workspace/play/app/controllers/start_controller.rb
class StartController < ApplicationController

  def index
  end

end


# if @contact_form.deliver
#   flash[:notice] = "You message has been successfully sent. We will contact you very soon!"
#   redirect_to root_path
# end

guess_my_words_workspace/play/app/helpers/application_helper.rb
module ApplicationHelper
end

guess_my_words_workspace/play/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Guess words</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

guess_my_words_workspace/play/app/views/plays/index.html.haml
- get_word = @all_words.sample
- word = get_word.gsub(/./){|s| s.send(%i[upcase downcase].sample)}

%p
  arrange this alphabeth to be true word:
  = word
%p
  Jawab:
= simple_form_for :play, url: plays_path, method: :get do |f|
  = f.input :guess
  = f.hidden_field :keyword, value: "#{get_word}"
  = f.button :submit, "submit"

- if flash[:success]
  = flash[:success]
- else
  = flash[:danger]

guess_my_words_workspace/play/app/views/start/index.html.haml
= link_to "GUESS WORDS ! click here" , plays_path